GET http://localhost:3000/usuarios
###
POST http://localhost:3000/usuarios
content-type: application/json

{
    "nome":"john doe",
    "email":"john.doe@gmail.com",
    "dataDeAniversario":"12/03/1999",
    "morada":"Logo ali",
    "telefone":"123123",
    "stack":"Front-end",
    "sobre":"Sou lindo"
}
###
PUT http://localhost:3000/usuarios/0f5ed0d5-6d93-4207-8552-4df03c59ec4b
Content-Type: application/json

{
    "nome":"john asdasdasdoe",
    "email":"john.asdasdasdoe@gmail.com",
    "dataDeAniversario":"12dasdasdasd/03/1999",
    "morada":"Logasdasdasdo ali",
    "telefone":"12asdasda3123",
    "stack":"Fronsdasdasdt-end",
    "sobre":"Sou asdaslindo"
}
###
PATCH http://localhost:3000/usuarios/1238f07b-2f3c-4979-af00-4bf22b644528
Content-Type: application/json

{
    "telefone":"0990123901",
    "stack":"Back-end",
    "sobre":"Sou feio"
}
###
DELETE http://localhost:3000/usuarios/1238f07b-2f3c-4979-af00-4bf22b644528